version: '3'

services:
  b2b_chat_wsgi:
    container_name: b2b_chat_wsgi_server
    build:
      context: ../../
      dockerfile: ./docker/deployment/dockerfiles/Dockerfile-app
    volumes:
      - ../../:/app:z
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - supervisor
    command: bash -c "python manage.py init_app && gunicorn config.asgi -b 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker --reload"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  supervisor:
    build:
      context: ../../
      dockerfile: ./docker/deployment/dockerfiles/Dockerfile-app
    volumes:
      - ../../:/app:z
    env_file:
      - ../../.env
    ports:
      - "5555:5555"
      - "9001:9001"
    depends_on:
      - redis
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

networks:
  default:
    external:
      name: iiht_b2b_chat
