# Generated by Django 4.2.3 on 2023-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_user_options_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_expert",
            field=models.BooleanField(default=False),
        ),
    ]
