# Generated by Django 4.2.3 on 2023-12-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_room_is_course_group_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="room",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
    ]
