# Generated by Django 4.2.3 on 2024-05-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_courseexpert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='idp_id',
            new_name='tenant_id',
        ),
    ]
