# Generated by Django 4.2.3 on 2024-05-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_idp_id_tenant_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(),
        ),
    ]
