# Generated by Django 4.2.3 on 2024-05-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_tenant_tenant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idp_id',
            new_name='user_id',
        ),
    ]
