# Generated by Django 4.2.3 on 2024-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.URLField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(default=None, max_length=512, null=True),
        ),
    ]
